# Generated by Django 4.0.3 on 2022-04-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='teaser',
            field=models.CharField(default='', max_length=300),
        ),
    ]
